version: '2'
services:
    app:
        container_name: sync
        build:
            context: .
        image: syncthing:bilenkis
        hostname: data.bilenkis.ru
        restart: always
        environment:
            - "PUID=107"
            - "PGID=1006"
        ports:
            - "8384:8384"
            - "22000:22000"
        volumes:
            - "./.config:/home/syncthing/.config"
            - "/data/sync/music-bilen:/home/syncthing/music-bilen"
            - "/data/galery:/home/syncthing/galery:ro"
